name: Deploy Linux Lab

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Remove old repository
        run: |
          sudo rm -rf /opt/Linux-Lab-Master

      - name: Clone latest repository
        run: |
          sudo git clone https://github.com/Shivam-yd/Linux-Lab-Master.git /opt/Linux-Lab-Master

      - name: Fix permissions
        run: |
          sudo chown -R github-runner:github-runner /opt/Linux-Lab-Master

      - name: Run installer
        run: |
          cd /opt/Linux-Lab-Master
          sudo bash installer/install.sh
